### ISSUE TITLE
make it golang

### ISSUE THREAD

**Issue by gedw99** [Foxboron/swtpm_test#1]
https://github.com/remko/age-plugin-se/tree/main/Sources 
- its swift.

we can port the code to golang and make it no ops for all other OS's- just call Apple Foundation , etc 

https://github.com/gioui/gio-x/blob/main/notify/macos/notify_macos.go

---

https://github.com/gioui/gio-x/tree/main/explorer is more extensive but no needed.
https://github.com/gioui/gio-x/blob/main/explorer/explorer_macos.go

## no cgo

also a good way :)

https://github.com/ebitengine/purego/blob/main/examples/objc/main_darwin.go

**Comment by Foxboron** [comment]
This is not going to be actionable as the t2/secure enclave chip does not have any software implementations that runs on Linux.

Sorry, closing.
